language: c

os: linux
dist: trusty
sudo: required

before_install:
  - if [[ "$INSTALL_ARM_DEPS" == "yes" ]]; then tools/apt-get-install-arm.sh; tools/install-bluez-arm.sh; fi
  - if [[ "$INSTALL_NUTTX_DEPS" == "yes" ]]; then tools/apt-get-install-nuttx.sh; fi
  - tools/apt-get-install-deps.sh
  - deps/jerry/tools/apt-get-install-deps.sh

install:

script: "tools/precommit.py $OPTS"

env:
  - OPTS="--test=host --buildtype=release"
  - OPTS="--test=host --buildtype=debug"
  - OPTS="--test=rpi2" INSTALL_ARM_DEPS=yes
  - OPTS="--test=nuttx" INSTALL_NUTTX_DEPS=yes
  - OPTS="--test=misc"
